#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Add a parameter to already existing parameter file(s).

The script will search recursively from the calling directory for
parameter files. If a root name is provided, however, then the script
will only operate on pf files which have the same root name.
"""

import argparse as ap

from pysi import find
from pysi.simulation import grid


def main():
    """Main function."""

    p = ap.ArgumentParser(description=__doc__)

    p.add_argument("parameter", help="Name of the parameter to add.")
    p.add_argument("value", help="The value for the new parameter.")
    p.add_argument("--root", default=None, help="Add the parameter to parameter files with this specific root name.")
    p.add_argument("--after", default=None, help="Insert the new parameter after another parameter.")

    args = p.parse_args()

    if args.root is None:
        root = "*"
    else:
        root = args.root

    for filepath in find(f"{root}.pf", "."):
        grid.add_parameter(filepath, args.parameter, args.value, args.after, verbose=True)

    return


if __name__ == "__main__":
    main()
