#!/usr/bin/env python3
# -*- coding: utf-8 -*-

import argparse
from pypython import cleanup_data

p = argparse.ArgumentParser(description="Remove 'data' symbolic links recursively.")
p.add_argument("-fp", default=".", help="The directory to search from")
args = p.parse_args()
print(f"{cleanup_data(args.fp)} symbolic links were removed")
