#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Print the errors for a set of Python simulations.

The purpose of this script is to collate the errors over all of the MPI
processes for a bunch of simulations.
"""

import sys
from pysi import find, get_root_name
from pysi.simulation import model_error_summary

parameter_files = find("*.pf")

if len(parameter_files) == 0:
    print("No Python models were found")
    sys.exit(1)
else:
    for pf in parameter_files:
        print("-" * 80)
        root, fp = get_root_name(pf)
        if fp.find("continuum") != -1:
            continue
        model_error_summary(root, fp, print_errors=True)

    print("-" * 80)
