#!/usr/bin/env python
# -*- coding: utf-8 -*-

"""Create wind save tables for a model.

This script will overwrite any previously created wind save table.
Verbose printing is on by default, but can be suppressed.
"""

import argparse as ap

import pypython

p = ap.ArgumentParser(description=__doc__)
p.add_argument("root", help="The root name of the simulation")
p.add_argument("-fp", "--filepath", default=".", help="The directory containing the simulation")
p.add_argument("-v", "--version", default=None, help="The version of windsave2table to use")
p.add_argument("-l", "--loud", default=False, action="store_true", help="Suppress the output from the script")
args = p.parse_args()

# ion fractions
pypython.create_wind_save_tables(args.root, args.filepath, False, False, args.version, args.loud)
# ion densities
pypython.create_wind_save_tables(args.root, args.filepath, True, False, args.version, args.loud)
# cell spectra
pypython.create_wind_save_tables(args.root, args.filepath, False, True, args.version, args.loud)
