#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""Create wind save tables for a model.

This script will overwrite any previously created wind save table.
Verbose printing is on by default, but can be suppressed.
"""

import argparse as ap

import pypython


def setup():
    """Setup the script.

    argparse is used to get parameters from the command line.
    """

    p = ap.ArgumentParser(description=__doc__)
    p.add_argument("root", help="The root name of the simulation")
    p.add_argument("-fp", "--filepath", default=".", help="The directory containing the simulation")
    p.add_argument("-v", "--version", default=None, help="The version of windsave2table to use")
    p.add_argument("-l", "--loud", default=False, action="store_true", help="Suppress the output from the script")

    args = p.parse_args()

    return args.root, args.filepath, args.version, args.loud


def main():
    """Main function of the script."""

    root, fp, version, loud = setup()

    # ion fractions
    pypython.create_wind_save_tables(root, fp, False, False, version, loud)
    # ion densities
    pypython.create_wind_save_tables(root, fp, True, False, version, loud)
    # cell spectra
    # pypython.create_wind_save_tables(root, fp, False, True, version, loud)

    return


if __name__ == "__main__":
    main()
