#!/usr/bin/env python3
# -*- coding: utf-8 -*-

"""Clear all jobs in the Slurm queue.

This does not discriminate, and will remove **everything** in the queue, so
use at your own peril knowing what can happen.
"""

import pypython

sh = pypython.run_command(["squeue", "-u", "$USER", "-o", "'%A'"])
job_ids = sh.stdout.decode("utf-8").split()[1:]

for job in job_ids:
    sh = pypython.run_command(["scancel", str(job)])
    if sh.stderr:
        print(sh.stderr.decode("utf-8"))

print(f"Removed jobs {', '.join(job_ids[:-1])} and {job_ids[-1]}.")
